root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/app ./cmd/server/..."
  entrypoint = "tmp/app"        # replaces deprecated full_bin and bin
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]