FROM golang:1.26-alpine

WORKDIR /app

RUN apk add --no-cache git

# Install air
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

# Don't copy source code here
# It will be mounted as volume

EXPOSE 8011

CMD ["air"]